### ISSUE TITLE
Moving ETN to an exchange from etn-sc

### ISSUE THREAD

**Issue by jimccadm** [electroneum/electroneum-sc#29]
Migration 100% complete - thanks dev team!

Can you detail please how ETN can be moved to an exchange via the command line wallet on ubuntu in the guides please? I am presuming it is a one-liner, but spelling that out could be really useful to CLI users. 

Thank you.

**Comment by andrepatta** [comment]
You should use `clef` for interacting with your wallet via CLI. Here's the documentation: https://developer.electroneum.com/etn-sc-client/tools/clef

Keep in mind that interacting with the CLI is meant for experienced & technical users.
