### ISSUE TITLE
Metamask claims wrong chain ID

### ISSUE THREAD

**Issue by sopha80** [electroneum/electroneum-sc#30]
both when running local ETN-SC 5.0.0.4 as well as connecting Electroneum mainnetvia chainlist.wtf to Metamask, Metamask gives error that the chain ID would be wrong.

![image](https://github.com/electroneum/electroneum-sc/assets/72129796/8b572cde-cb8b-43ab-8c7e-9d1791cb84e0)

**Comment by andrepatta** [comment]
`api.electroneum.com` is not available yet. 

We are working as fast as possible to get a public node service online, but in the meantime you should run a local node to connect Metamask.
